package com.github.fromi.chess.material.util;

import static com.github.fromi.chess.material.Square.SQUARES;

import com.github.fromi.chess.material.Square;

@SuppressWarnings("UnusedDeclaration")
public class Squares {
    public static final Square A1 = SQUARES.get('a', 1);
    public static final Square A2 = SQUARES.get('a', 2);
    public static final Square A3 = SQUARES.get('a', 3);
    public static final Square A4 = SQUARES.get('a', 4);
    public static final Square A5 = SQUARES.get('a', 5);
    public static final Square A6 = SQUARES.get('a', 6);
    public static final Square A7 = SQUARES.get('a', 7);
    public static final Square A8 = SQUARES.get('a', 8);
    public static final Square B1 = SQUARES.get('b', 1);
    public static final Square B2 = SQUARES.get('b', 2);
    public static final Square B3 = SQUARES.get('b', 3);
    public static final Square B4 = SQUARES.get('b', 4);
    public static final Square B5 = SQUARES.get('b', 5);
    public static final Square B6 = SQUARES.get('b', 6);
    public static final Square B7 = SQUARES.get('b', 7);
    public static final Square B8 = SQUARES.get('b', 8);
    public static final Square C1 = SQUARES.get('c', 1);
    public static final Square C2 = SQUARES.get('c', 2);
    public static final Square C3 = SQUARES.get('c', 3);
    public static final Square C4 = SQUARES.get('c', 4);
    public static final Square C5 = SQUARES.get('c', 5);
    public static final Square C6 = SQUARES.get('c', 6);
    public static final Square C7 = SQUARES.get('c', 7);
    public static final Square C8 = SQUARES.get('c', 8);
    public static final Square D1 = SQUARES.get('d', 1);
    public static final Square D2 = SQUARES.get('d', 2);
    public static final Square D3 = SQUARES.get('d', 3);
    public static final Square D4 = SQUARES.get('d', 4);
    public static final Square D5 = SQUARES.get('d', 5);
    public static final Square D6 = SQUARES.get('d', 6);
    public static final Square D7 = SQUARES.get('d', 7);
    public static final Square D8 = SQUARES.get('d', 8);
    public static final Square E1 = SQUARES.get('e', 1);
    public static final Square E2 = SQUARES.get('e', 2);
    public static final Square E3 = SQUARES.get('e', 3);
    public static final Square E4 = SQUARES.get('e', 4);
    public static final Square E5 = SQUARES.get('e', 5);
    public static final Square E6 = SQUARES.get('e', 6);
    public static final Square E7 = SQUARES.get('e', 7);
    public static final Square E8 = SQUARES.get('e', 8);
    public static final Square F1 = SQUARES.get('f', 1);
    public static final Square F2 = SQUARES.get('f', 2);
    public static final Square F3 = SQUARES.get('f', 3);
    public static final Square F4 = SQUARES.get('f', 4);
    public static final Square F5 = SQUARES.get('f', 5);
    public static final Square F6 = SQUARES.get('f', 6);
    public static final Square F7 = SQUARES.get('f', 7);
    public static final Square F8 = SQUARES.get('f', 8);
    public static final Square G1 = SQUARES.get('g', 1);
    public static final Square G2 = SQUARES.get('g', 2);
    public static final Square G3 = SQUARES.get('g', 3);
    public static final Square G4 = SQUARES.get('g', 4);
    public static final Square G5 = SQUARES.get('g', 5);
    public static final Square G6 = SQUARES.get('g', 6);
    public static final Square G7 = SQUARES.get('g', 7);
    public static final Square G8 = SQUARES.get('g', 8);
    public static final Square H1 = SQUARES.get('h', 1);
    public static final Square H2 = SQUARES.get('h', 2);
    public static final Square H3 = SQUARES.get('h', 3);
    public static final Square H4 = SQUARES.get('h', 4);
    public static final Square H5 = SQUARES.get('h', 5);
    public static final Square H6 = SQUARES.get('h', 6);
    public static final Square H7 = SQUARES.get('h', 7);
    public static final Square H8 = SQUARES.get('h', 8);
}
